<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Venue extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'type',
        'capacity',
        'price',
        'location',
        'amenities',
        'description',
        'image_url',
        'status',
    ];

    protected $casts = [
        'amenities' => 'array',
        'price' => 'decimal:2',
    ];

    /**
     * Get all reservations for this venue
     */
    public function reservations(): HasMany
    {
        return $this->hasMany(Reservation::class);
    }

    /**
     * Check if the venue is available for a specific date and time
     */
    public function isAvailable(string $date, string $startTime, string $endTime): bool
    {
        return $this->reservations()
            ->where('date', $date)
            ->where(function ($query) use ($startTime, $endTime) {
                $query->where(function ($q) use ($startTime, $endTime) {
                    $q->where('start_time', '<', $endTime)
                      ->where('end_time', '>', $startTime);
                });
            })
            ->where('status', '!=', 'cancelled')
            ->count() === 0;
    }

    /**
     * Get the revenue generated by this venue
     */
    public function revenue()
    {
        return $this->reservations()
            ->where('status', 'confirmed')
            ->sum('total_amount');
    }

    /**
     * Get the number of bookings for this venue
     */
    public function bookingsCount()
    {
        return $this->reservations()
            ->where('status', 'confirmed')
            ->count();
    }
}
